package tmsc

import "testing"

func TestGFTables(t *testing.T) {
	// α^0 = 1
	if gfExp[0] != 1 {
		t.Errorf("gfExp[0] = %d, want 1", gfExp[0])
	}
	// α^1 = 2
	if gfExp[1] != 2 {
		t.Errorf("gfExp[1] = %d, want 2", gfExp[1])
	}
	// α^255 = 1 (primitive element has order 255)
	if gfExp[255] != 1 {
		t.Errorf("gfExp[255] = %d, want 1", gfExp[255])
	}
	// gfLog[1] = 0
	if gfLog[1] != 0 {
		t.Errorf("gfLog[1] = %d, want 0", gfLog[1])
	}
}

func TestGFMul(t *testing.T) {
	// Multiplication by zero
	if gfMul(0, 42) != 0 {
		t.Error("gfMul(0, x) should be 0")
	}
	if gfMul(42, 0) != 0 {
		t.Error("gfMul(x, 0) should be 0")
	}
	// Multiplication by 1
	if gfMul(1, 42) != 42 {
		t.Error("gfMul(1, x) should be x")
	}
	// Commutativity
	if gfMul(37, 89) != gfMul(89, 37) {
		t.Error("gfMul should be commutative")
	}
}

func TestGFInverse(t *testing.T) {
	// a * a^{-1} = 1 for all nonzero a
	for a := 1; a < 256; a++ {
		inv := gfInv(byte(a))
		product := gfMul(byte(a), inv)
		if product != 1 {
			t.Errorf("gfMul(%d, gfInv(%d)) = %d, want 1", a, a, product)
		}
	}
}

func TestGFFieldClosure(t *testing.T) {
	// Verify all 255 nonzero elements are generated by alpha
	seen := make(map[byte]bool)
	for i := 0; i < 255; i++ {
		seen[gfExp[i]] = true
	}
	if len(seen) != 255 {
		t.Errorf("Field generator produced %d unique elements, want 255", len(seen))
	}
	if seen[0] {
		t.Error("Zero should not be generated by alpha powers")
	}
}

func TestGFPow(t *testing.T) {
	if gfPow(0) != 1 {
		t.Errorf("gfPow(0) = %d, want 1", gfPow(0))
	}
	if gfPow(1) != 2 {
		t.Errorf("gfPow(1) = %d, want 2", gfPow(1))
	}
	// Negative exponent wraps correctly
	if gfPow(-1) != gfPow(254) {
		t.Errorf("gfPow(-1) = %d, want gfPow(254) = %d", gfPow(-1), gfPow(254))
	}
}
