package odm_test

import (
	"errors"
	"math"
	"testing"
	"time"

	"github.com/ravisuhag/astro/pkg/odm"
)

// Figure G-1 of CCSDS 502.0-B-3, transcribed. The alignment is the document's,
// because clauses 7.4.5 to 7.4.7 make it insignificant and a reader has to
// prove that rather than assume it.
const figureG1 = `CCSDS_OPM_VERS = 3.0
CREATION_DATE = 2022-11-06T09:23:57
ORIGINATOR     = JAXA

COMMENT          GEOCENTRIC, CARTESIAN, EARTH FIXED
OBJECT_NAME    = OSPREY 5
OBJECT_ID      = 1998-999A
CENTER_NAME    = EARTH
REF_FRAME      = ITRF2000
TIME_SYSTEM    = UTC

EPOCH =           2022-12-18T14:28:15.1172
X =               6503.514000
Y =               1239.647000
Z =               -717.490000
X_DOT =             -0.873160
Y_DOT =              8.740420
Z_DOT =             -4.191076
MASS =            3000.000000
SOLAR_RAD_AREA =    18.770000
SOLAR_RAD_COEFF =    1.000000
DRAG_AREA =         18.770000
DRAG_COEFF =         2.500000
`

func TestDecodeSimpleOPM(t *testing.T) {
	m, err := odm.DecodeOPM([]byte(figureG1))
	if err != nil {
		t.Fatalf("DecodeOPM: %v", err)
	}

	if m.Header.Version != "3.0" {
		t.Errorf("Version = %q, want 3.0", m.Header.Version)
	}
	if m.Header.Originator != "JAXA" {
		t.Errorf("Originator = %q, want JAXA", m.Header.Originator)
	}
	wantCreated := time.Date(2022, 11, 6, 9, 23, 57, 0, time.UTC)
	if !m.Header.CreationDate.Equal(wantCreated) {
		t.Errorf("CreationDate = %v, want %v", m.Header.CreationDate, wantCreated)
	}

	// The COMMENT sits after ORIGINATOR, so it opens the metadata section
	// rather than the header (clause 7.8.7).
	if len(m.Header.Comments) != 0 {
		t.Errorf("header comments = %q, want none", m.Header.Comments)
	}
	if len(m.Metadata.Comments) != 1 ||
		m.Metadata.Comments[0] != "         GEOCENTRIC, CARTESIAN, EARTH FIXED" {
		t.Errorf("metadata comments = %q", m.Metadata.Comments)
	}

	md := m.Metadata
	if md.ObjectName != "OSPREY 5" || md.ObjectID != "1998-999A" ||
		md.CenterName != "EARTH" || md.RefFrame != "ITRF2000" || md.TimeSystem != "UTC" {
		t.Errorf("metadata = %+v", md)
	}

	sv := m.Data.StateVector
	wantEpoch := time.Date(2022, 12, 18, 14, 28, 15, 117200000, time.UTC)
	if !sv.Epoch.Equal(wantEpoch) {
		t.Errorf("Epoch = %v, want %v", sv.Epoch, wantEpoch)
	}
	for _, tt := range []struct {
		name string
		got  float64
		want float64
	}{
		{"X", sv.X, 6503.514},
		{"Y", sv.Y, 1239.647},
		{"Z", sv.Z, -717.49},
		{"X_DOT", sv.XDot, -0.87316},
		{"Y_DOT", sv.YDot, 8.74042},
		{"Z_DOT", sv.ZDot, -4.191076},
	} {
		if tt.got != tt.want {
			t.Errorf("%s = %v, want %v", tt.name, tt.got, tt.want)
		}
	}

	if m.Data.Keplerian != nil {
		t.Error("a Keplerian block was read from a message that has none")
	}
	s := m.Data.Spacecraft
	if s == nil {
		t.Fatal("no spacecraft parameters")
	}
	if !s.HasMass() || s.Mass != 3000 {
		t.Errorf("Mass = %v (given %v), want 3000", s.Mass, s.HasMass())
	}
	if s.SolarRadArea != 18.77 || s.SolarRadCoeff != 1 || s.DragArea != 18.77 || s.DragCoeff != 2.5 {
		t.Errorf("spacecraft parameters = %+v", s)
	}
}

// The second example in annex G: state, Keplerian elements, spacecraft
// parameters and two manoeuvres, with units written out and comments opening
// most of the blocks.
const figureG2 = `CCSDS_OPM_VERS     =   3.0

COMMENT   Generated by GSOC, R. Kiehling
COMMENT   Current intermediate orbit IO2 and maneuver planning data

CREATION_DATE      =   2021-06-03T05:33:00.000
ORIGINATOR         =   GSOC

OBJECT_NAME        =   EUTELSAT W4
OBJECT_ID          =   2021-028A
CENTER_NAME        =   EARTH
REF_FRAME          =   TOD
TIME_SYSTEM        =   UTC

COMMENT   State Vector
EPOCH              = 2021-06-03T00:00:00.000
X                  =   6655.9942        [km]
Y                  = -40218.5751        [km]
Z                  =    -82.9177        [km]
X_DOT              =      3.11548208    [km/s]
Y_DOT              =      0.47042605    [km/s]
Z_DOT              =     -0.00101495    [km/s]

COMMENT Keplerian elements
SEMI_MAJOR_AXIS   =  41399.5123            [km]
ECCENTRICITY      =      0.020842611
INCLINATION       =      0.117746          [deg]
RA_OF_ASC_NODE    =     17.604721          [deg]
ARG_OF_PERICENTER =    218.242943          [deg]
TRUE_ANOMALY      =     41.922339          [deg]
GM                = 398600.4415            [km**3/s**2]

COMMENT Spacecraft parameters
MASS             =    1913.000             [kg]
SOLAR_RAD_AREA   =      10.000             [m**2]
SOLAR_RAD_COEFF  =       1.300
DRAG_AREA        =      10.000             [m**2]
DRAG_COEFF       =       2.300

COMMENT   2 planned maneuvers

COMMENT First maneuver: AMF-3
COMMENT Non-impulsive, thrust direction fixed in inertial frame
MAN_EPOCH_IGNITION =     2021-06-03T09:00:34.1
MAN_DURATION      =    132.60          [s]
MAN_DELTA_MASS    =    -18.418         [kg]
MAN_REF_FRAME     =      EME2000
MAN_DV_1          =     -0.02325700    [km/s]
MAN_DV_2          =      0.01683160    [km/s]
MAN_DV_3          =     -0.00893444    [km/s]

COMMENT Second maneuver: first station acquisition maneuver
COMMENT impulsive, thrust direction fixed in RTN frame
MAN_EPOCH_IGNITION =     2021-06-05T18:59:21.0
MAN_DURATION      =      0.00          [s]
MAN_DELTA_MASS    =     -1.469         [kg]
MAN_REF_FRAME     =      RTN
MAN_DV_1          =      0.00101500    [km/s]
MAN_DV_2          =     -0.00187300    [km/s]
MAN_DV_3          =      0.00000000    [km/s]
`

func TestDecodeOPMWithManeuvers(t *testing.T) {
	m, err := odm.DecodeOPM([]byte(figureG2))
	if err != nil {
		t.Fatalf("DecodeOPM: %v", err)
	}

	// These comments come between the version keyword and CREATION_DATE, which
	// is the only place a header comment may sit.
	if len(m.Header.Comments) != 2 {
		t.Errorf("header comments = %q, want 2", m.Header.Comments)
	}

	// Units are documentation, not data: the value is the same with or
	// without '[km]' after it (clause 7.7.1.1).
	sv := m.Data.StateVector
	if sv.X != 6655.9942 || sv.Y != -40218.5751 || sv.Z != -82.9177 {
		t.Errorf("position = %v %v %v", sv.X, sv.Y, sv.Z)
	}
	if sv.XDot != 3.11548208 || sv.YDot != 0.47042605 || sv.ZDot != -0.00101495 {
		t.Errorf("velocity = %v %v %v", sv.XDot, sv.YDot, sv.ZDot)
	}

	k := m.Data.Keplerian
	if k == nil {
		t.Fatal("no Keplerian elements")
	}
	if k.SemiMajorAxis != 41399.5123 || k.Eccentricity != 0.020842611 || k.GM != 398600.4415 {
		t.Errorf("Keplerian elements = %+v", k)
	}
	if k.AnomalyIsMean {
		t.Error("the anomaly was read as a mean anomaly; the message gives TRUE_ANOMALY")
	}
	if k.Anomaly != 41.922339 {
		t.Errorf("Anomaly = %v, want 41.922339", k.Anomaly)
	}

	if len(m.Data.Maneuvers) != 2 {
		t.Fatalf("read %d maneuvers, want 2", len(m.Data.Maneuvers))
	}

	first := m.Data.Maneuvers[0]
	wantIgnition := time.Date(2021, 6, 3, 9, 0, 34, 100000000, time.UTC)
	if !first.EpochIgnition.Equal(wantIgnition) {
		t.Errorf("first ignition = %v, want %v", first.EpochIgnition, wantIgnition)
	}
	if first.Duration != 132.60 || first.DeltaMass != -18.418 || first.RefFrame != "EME2000" {
		t.Errorf("first maneuver = %+v", first)
	}
	if first.DV != [3]float64{-0.023257, 0.0168316, -0.00893444} {
		t.Errorf("first DV = %v", first.DV)
	}
	// Three, not two. The document writes "COMMENT 2 planned maneuvers" ahead
	// of the first maneuver's own two comment lines, meaning it for the whole
	// group. Nothing in the format says so: clause 7.8.7 attaches a comment to
	// the logical block that follows it, and each maneuver is its own block,
	// so all three land on the first one. A reader cannot recover the author's
	// intent here, and neither can this package.
	if len(first.Comments) != 3 {
		t.Errorf("first maneuver comments = %q, want 3", first.Comments)
	}

	// Clause 3.2.4.7: a zero duration marks an impulsive manoeuvre.
	second := m.Data.Maneuvers[1]
	if second.Duration != 0 {
		t.Errorf("second duration = %v, want 0 for an impulsive maneuver", second.Duration)
	}
	if second.RefFrame != "RTN" {
		t.Errorf("second frame = %q, want RTN", second.RefFrame)
	}
}

// Encoding and decoding must agree on the values. The octets will not match
// the document's, because clause 7.5.6 makes trailing zeroes optional and
// clauses 7.4.5 to 7.4.7 make the alignment insignificant, so the same message
// has many spellings.
func TestOPMRoundTrip(t *testing.T) {
	for name, input := range map[string]string{"figure G-1": figureG1, "figure G-2": figureG2} {
		t.Run(name, func(t *testing.T) {
			first, err := odm.DecodeOPM([]byte(input))
			if err != nil {
				t.Fatalf("DecodeOPM: %v", err)
			}
			encoded, err := first.Encode()
			if err != nil {
				t.Fatalf("Encode: %v", err)
			}
			second, err := odm.DecodeOPM(encoded)
			if err != nil {
				t.Fatalf("DecodeOPM on our own output: %v\n%s", err, encoded)
			}

			if !second.Data.StateVector.Epoch.Equal(first.Data.StateVector.Epoch) {
				t.Errorf("epoch changed: %v then %v",
					first.Data.StateVector.Epoch, second.Data.StateVector.Epoch)
			}
			compare(t, "X", first.Data.StateVector.X, second.Data.StateVector.X)
			compare(t, "Z_DOT", first.Data.StateVector.ZDot, second.Data.StateVector.ZDot)

			if len(second.Data.Maneuvers) != len(first.Data.Maneuvers) {
				t.Fatalf("maneuver count changed: %d then %d",
					len(first.Data.Maneuvers), len(second.Data.Maneuvers))
			}
			for i := range first.Data.Maneuvers {
				compare(t, "delta mass", first.Data.Maneuvers[i].DeltaMass, second.Data.Maneuvers[i].DeltaMass)
				compare(t, "DV 1", first.Data.Maneuvers[i].DV[0], second.Data.Maneuvers[i].DV[0])
			}
		})
	}
}

func compare(t *testing.T, name string, want, got float64) {
	t.Helper()
	if math.Abs(got-want) > 1e-12*math.Max(1, math.Abs(want)) {
		t.Errorf("%s changed: %v then %v", name, want, got)
	}
}

func TestDecodeOPMRejects(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  error
	}{
		{
			name:  "a keyword no table lists",
			input: figureG1 + "NOT_A_KEYWORD = 1\n",
			want:  odm.ErrUnknownKeyword,
		},
		{
			name:  "a repeated keyword",
			input: figureG1 + "DRAG_COEFF = 2.5\n",
			want:  odm.ErrDuplicateKeyword,
		},
		{
			name:  "both anomalies",
			input: figureG2 + "MEAN_ANOMALY = 41.0\n",
			want:  odm.ErrBothAnomalies,
		},
		{
			name:  "a maneuver parameter before its ignition epoch",
			input: figureG1 + "MAN_DURATION = 10.0\n",
			want:  odm.ErrKeywordOutOfOrder,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := odm.DecodeOPM([]byte(tt.input)); !errors.Is(err, tt.want) {
				t.Errorf("DecodeOPM = %v, want %v", err, tt.want)
			}
		})
	}
}

// Clause 3.2.4.9 makes mass mandatory once a manoeuvre is present, and
// clause 3.2.4.7 requires the mass change to be negative.
func TestOPMManeuverRules(t *testing.T) {
	base, err := odm.DecodeOPM([]byte(figureG2))
	if err != nil {
		t.Fatalf("DecodeOPM: %v", err)
	}

	t.Run("a maneuver without mass", func(t *testing.T) {
		m := *base
		data := m.Data
		data.Spacecraft = nil
		m.Data = data
		if err := m.Validate(); !errors.Is(err, odm.ErrManeuverWithoutMass) {
			t.Errorf("Validate = %v, want ErrManeuverWithoutMass", err)
		}
	})

	t.Run("a maneuver that gains mass", func(t *testing.T) {
		m := *base
		maneuvers := append([]odm.Maneuver(nil), m.Data.Maneuvers...)
		maneuvers[0].DeltaMass = 1.0
		data := m.Data
		data.Maneuvers = maneuvers
		m.Data = data
		if err := m.Validate(); !errors.Is(err, odm.ErrDeltaMassNotNegative) {
			t.Errorf("Validate = %v, want ErrDeltaMassNotNegative", err)
		}
	})
}
