package aos

// Frame Header Error Control (CCSDS 732.0-B-4 clause 4.1.2.6).
//
// The optional FHEC is a 16-bit field occupying bits 48-63 of the primary
// header (octets 6-7, extending the header to 8 octets). It protects the
// Master Channel Identifier, the Virtual Channel Identifier, and the
// Signaling Field with a shortened Reed-Solomon (10,6) code over GF(2^4):
//
//   - J=4 bits per symbol, E=2 symbol error correction capability;
//   - field generator polynomial F(x) = x^4 + x + 1;
//   - code generator polynomial g(x) = x^4 + α^3|x^3 + α|x^2 + α^3|x + 1
//     (roots α^6..α^9).
//
// Header bits map to symbols as (clause 4.1.2.6.5 f):
//
//	bits  0-15  -> symbols 0-3  (octets 0-1: TFVN, SCID, VCID)
//	bits 40-47  -> symbols 4-5  (octet 5: signaling field)
//	bits 48-63  -> symbols 6-9  (octets 6-7: the FHEC check symbols)
//
// This implementation generates check symbols on encode and detects
// errors on decode by recomputing them. Error correction (up to E=2
// symbols) is not performed: a frame whose protected header octets do
// not match its FHEC is rejected.

// FHECSize is the size of the Frame Header Error Control field in bytes.
const FHECSize = 2

// gf16Exp and gf16Log are the antilog/log tables for GF(2^4) generated by
// α (=0b0010) under the field polynomial x^4 + x + 1.
var gf16Exp [30]uint8
var gf16Log [16]uint8

func init() {
	x := uint8(1)
	for i := 0; i < 15; i++ {
		gf16Exp[i] = x
		gf16Exp[i+15] = x
		gf16Log[x] = uint8(i)
		x <<= 1
		if x&0x10 != 0 {
			x ^= 0x13 // reduce by x^4 + x + 1
		}
	}
}

// gf16Mul multiplies two GF(2^4) elements.
func gf16Mul(a, b uint8) uint8 {
	if a == 0 || b == 0 {
		return 0
	}
	return gf16Exp[gf16Log[a]+gf16Log[b]]
}

// fhecGenerator holds the coefficients of g(x) below the monic leading
// term, ordered x^3, x^2, x^1, x^0: α^3, α, α^3, 1.
var fhecGenerator = [4]uint8{0x8, 0x2, 0x8, 0x1}

// computeFHECParity returns the four RS(10,6) check symbols for the six
// information symbols, computed as the remainder of x^4|m(x) mod g(x).
func computeFHECParity(info [6]uint8) [4]uint8 {
	var reg [4]uint8
	for _, s := range info {
		fb := s ^ reg[0]
		reg[0] = reg[1] ^ gf16Mul(fb, fhecGenerator[0])
		reg[1] = reg[2] ^ gf16Mul(fb, fhecGenerator[1])
		reg[2] = reg[3] ^ gf16Mul(fb, fhecGenerator[2])
		reg[3] = gf16Mul(fb, fhecGenerator[3])
	}
	return reg
}

// fhecInfoSymbols extracts the six protected information symbols from the
// first six octets of an encoded primary header.
func fhecInfoSymbols(header []byte) [6]uint8 {
	return [6]uint8{
		header[0] >> 4, header[0] & 0x0F,
		header[1] >> 4, header[1] & 0x0F,
		header[5] >> 4, header[5] & 0x0F,
	}
}

// ComputeFHEC returns the 2-octet Frame Header Error Control for an
// encoded 6-octet primary header.
func ComputeFHEC(header []byte) ([]byte, error) {
	if len(header) < PrimaryHeaderSize {
		return nil, ErrDataTooShort
	}
	p := computeFHECParity(fhecInfoSymbols(header))
	return []byte{p[0]<<4 | p[1], p[2]<<4 | p[3]}, nil
}

// VerifyFHEC reports whether the 2-octet FHEC matches the protected
// octets of the encoded 6-octet primary header.
func VerifyFHEC(header, fhec []byte) bool {
	if len(header) < PrimaryHeaderSize || len(fhec) < FHECSize {
		return false
	}
	p := computeFHECParity(fhecInfoSymbols(header))
	return fhec[0] == p[0]<<4|p[1] && fhec[1] == p[2]<<4|p[3]
}
