// Package cop implements the Communications Operation Procedure-1 (COP-1)
// per CCSDS 232.1-B-2.
//
// COP-1 provides reliable TC frame delivery over the space link using:
//   - FOP-1 (Flight Operations Procedure) on the ground side
//   - FARM-1 (Frame Acceptance and Reporting Mechanism) on the spacecraft side
//   - CLCW (Communications Link Control Word) for return-link status reporting
package cop

import "strings"

// CLCW represents the Communications Link Control Word (4 bytes / 32 bits).
// Per CCSDS 232.1-B-2 Section 4.2.
//
// The CLCW is generated by FARM-1 on the spacecraft and transported back
// to the ground via the TM Operational Control Field (OCF).
//
// Bit layout:
//
//	Byte 0: [CWType:1][Version:2][Status:3][COP:2]
//	Byte 1: [VCID:6][Reserved:2]
//	Byte 2: [NoRF:1][NoBitLock:1][Lockout:1][Wait:1][Retransmit:1][FARMB:2][spare:1]
//	Byte 3: [ReportValue:8]
type CLCW struct {
	ControlWordType   uint8 // 1 bit  - always 0 for CLCW
	Version           uint8 // 2 bits - always 00
	StatusField       uint8 // 3 bits - mission-specific status
	COPInEffect       uint8 // 2 bits - 01=COP-1
	VirtualChannelID  uint8 // 6 bits - VC this CLCW reports on
	Reserved          uint8 // 2 bits - spare
	NoRFAvailableFlag bool  // 1 bit
	NoBitLockFlag     bool  // 1 bit
	LockoutFlag       bool  // 1 bit  - FARM-1 lockout state
	WaitFlag          bool  // 1 bit  - FARM-1 wait state
	RetransmitFlag    bool  // 1 bit  - FARM-1 retransmit request
	FARMBCounter      uint8 // 2 bits - Type-B frame counter (0-3)
	ReportValue       uint8 // 8 bits - V(R): next expected frame sequence number
}

// Encode packs the CLCW into a 4-byte slice.
func (c *CLCW) Encode() ([]byte, error) {
	if err := c.Validate(); err != nil {
		return nil, err
	}

	b := make([]byte, 4)
	b[0] = (c.ControlWordType << 7) | (c.Version << 5) | (c.StatusField << 2) | (c.COPInEffect & 0x03)
	b[1] = (c.VirtualChannelID << 2) | (c.Reserved & 0x03)

	b[2] = 0
	if c.NoRFAvailableFlag {
		b[2] |= 1 << 7
	}
	if c.NoBitLockFlag {
		b[2] |= 1 << 6
	}
	if c.LockoutFlag {
		b[2] |= 1 << 5
	}
	if c.WaitFlag {
		b[2] |= 1 << 4
	}
	if c.RetransmitFlag {
		b[2] |= 1 << 3
	}
	b[2] |= (c.FARMBCounter & 0x03) << 1

	b[3] = c.ReportValue

	return b, nil
}

// Decode parses a 4-byte slice into the CLCW.
func (c *CLCW) Decode(data []byte) error {
	if len(data) < 4 {
		return ErrDataTooShort
	}

	c.ControlWordType = (data[0] >> 7) & 0x01
	c.Version = (data[0] >> 5) & 0x03
	c.StatusField = (data[0] >> 2) & 0x07
	c.COPInEffect = data[0] & 0x03
	c.VirtualChannelID = (data[1] >> 2) & 0x3F
	c.Reserved = data[1] & 0x03
	c.NoRFAvailableFlag = (data[2] & (1 << 7)) != 0
	c.NoBitLockFlag = (data[2] & (1 << 6)) != 0
	c.LockoutFlag = (data[2] & (1 << 5)) != 0
	c.WaitFlag = (data[2] & (1 << 4)) != 0
	c.RetransmitFlag = (data[2] & (1 << 3)) != 0
	c.FARMBCounter = (data[2] >> 1) & 0x03
	c.ReportValue = data[3]

	return c.Validate()
}

// Validate checks the CLCW fields.
func (c *CLCW) Validate() error {
	if c.ControlWordType != 0 {
		return ErrInvalidCLCWType
	}
	if c.Version != 0 {
		return ErrInvalidCLCWVersion
	}
	return nil
}

// Humanize returns a human-readable representation of the CLCW.
func (c *CLCW) Humanize() string {
	boolStr := func(b bool) string {
		if b {
			return "Yes"
		}
		return "No"
	}
	return strings.Join([]string{
		"  CLCW Version: 0",
		"  COP in Effect: " + string(rune('0'+c.COPInEffect)),
		"  VCID: " + string(rune('0'+c.VirtualChannelID/10)) + string(rune('0'+c.VirtualChannelID%10)),
		"  No RF Available: " + boolStr(c.NoRFAvailableFlag),
		"  No Bit Lock: " + boolStr(c.NoBitLockFlag),
		"  Lockout: " + boolStr(c.LockoutFlag),
		"  Wait: " + boolStr(c.WaitFlag),
		"  Retransmit: " + boolStr(c.RetransmitFlag),
		"  FARM-B Counter: " + string(rune('0'+c.FARMBCounter)),
		"  Report Value V(R): " + string(rune('0'+c.ReportValue/100)) +
			string(rune('0'+c.ReportValue/10%10)) + string(rune('0'+c.ReportValue%10)),
	}, "\n")
}
