package ndm

import (
	"errors"
	"testing"
	"time"
)

// opmSpec is how CCSDS 502.0-B-3 table 3-1 treats the shared header keywords.
var opmSpec = HeaderSpec{
	VersionKeyword: "CCSDS_OPM_VERS",
	Classification: Optional,
	MessageFor:     Absent,
	MessageID:      Optional,
}

// cdmSpec is how CCSDS 508.0-B-1 table 3-1 treats them. It is the odd one out
// twice over: MESSAGE_ID is mandatory rather than optional, MESSAGE_FOR exists
// only here, and CLASSIFICATION is not in the table at all.
var cdmSpec = HeaderSpec{
	VersionKeyword: "CCSDS_CDM_VERS",
	Classification: Absent,
	MessageFor:     Optional,
	MessageID:      Mandatory,
}

// The header of figure G-1 in CCSDS 502.0-B-3, transcribed.
func TestReadHeaderFromAWorkedExample(t *testing.T) {
	const input = "CCSDS_OPM_VERS = 3.0\n" +
		"CREATION_DATE = 2022-11-06T09:23:57\n" +
		"ORIGINATOR     = JAXA\n" +
		"\n" +
		"COMMENT          GEOCENTRIC, CARTESIAN, EARTH FIXED\n" +
		"OBJECT_NAME    = OSPREY 5\n"

	s := NewScanner([]byte(input), true)
	h, err := ReadHeader(s, opmSpec)
	if err != nil {
		t.Fatalf("ReadHeader: %v", err)
	}

	if h.Version != "3.0" {
		t.Errorf("Version = %q, want 3.0", h.Version)
	}
	if h.Originator != "JAXA" {
		t.Errorf("Originator = %q, want JAXA", h.Originator)
	}
	want := time.Date(2022, 11, 6, 9, 23, 57, 0, time.UTC)
	if !h.CreationDate.Equal(want) {
		t.Errorf("CreationDate = %v, want %v", h.CreationDate, want)
	}

	// The COMMENT here sits after ORIGINATOR, which puts it in the metadata
	// section rather than the header. ReadHeader must stop before it and hand
	// the line back.
	if len(h.Comments) != 0 {
		t.Errorf("Comments = %q, want none: the comment belongs to the metadata section", h.Comments)
	}
	if !s.Scan() {
		t.Fatal("the line after the header was not handed back")
	}
	if got := s.Line(); got.Kind != Comment {
		t.Errorf("next line is %v, want the COMMENT that starts the metadata", got.Kind)
	}
}

// The second example in annex G puts its comments between the version keyword
// and CREATION_DATE, which is where every standard's table allows them.
func TestReadHeaderWithComments(t *testing.T) {
	const input = "CCSDS_OPM_VERS     =   3.0\n" +
		"\n" +
		"COMMENT   Generated by GSOC, R. Kiehling\n" +
		"COMMENT   Current intermediate orbit IO2 and maneuver planning data\n" +
		"\n" +
		"CREATION_DATE      =   2021-06-03T05:33:00.000\n" +
		"ORIGINATOR         =   GSOC\n" +
		"\n" +
		"OBJECT_NAME        =   EUTELSAT W4\n"

	s := NewScanner([]byte(input), true)
	h, err := ReadHeader(s, opmSpec)
	if err != nil {
		t.Fatalf("ReadHeader: %v", err)
	}

	if len(h.Comments) != 2 {
		t.Fatalf("read %d comments, want 2", len(h.Comments))
	}
	if h.Comments[0] != "  Generated by GSOC, R. Kiehling" {
		t.Errorf("first comment = %q", h.Comments[0])
	}
	if h.Originator != "GSOC" {
		t.Errorf("Originator = %q, want GSOC", h.Originator)
	}
}

// Clause 7.3.6: the first header line must be the first non-blank line.
func TestReadHeaderRequiresTheVersionFirst(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  error
	}{
		{"empty file", "", ErrNoVersionLine},
		{"only blank lines", "\n\n\n", ErrNoVersionLine},
		{
			name:  "something before the version",
			input: "ORIGINATOR = JAXA\nCCSDS_OPM_VERS = 3.0\n",
			want:  ErrNoVersionLine,
		},
		{
			name:  "another message type's version",
			input: "CCSDS_OEM_VERS = 3.0\nCREATION_DATE = 2022-11-06T09:23:57\nORIGINATOR = JAXA\n",
			want:  ErrWrongMessageType,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := NewScanner([]byte(tt.input), true)
			if _, err := ReadHeader(s, opmSpec); !errors.Is(err, tt.want) {
				t.Errorf("ReadHeader = %v, want %v", err, tt.want)
			}
		})
	}
}

func TestReadHeaderRequiresMandatoryKeywords(t *testing.T) {
	tests := []struct {
		name  string
		input string
		spec  HeaderSpec
	}{
		{
			name:  "no CREATION_DATE",
			input: "CCSDS_OPM_VERS = 3.0\nORIGINATOR = JAXA\nOBJECT_NAME = X\n",
			spec:  opmSpec,
		},
		{
			name:  "no ORIGINATOR",
			input: "CCSDS_OPM_VERS = 3.0\nCREATION_DATE = 2022-11-06T09:23:57\nOBJECT_NAME = X\n",
			spec:  opmSpec,
		},
		{
			name: "no MESSAGE_ID, which a conjunction message makes mandatory",
			input: "CCSDS_CDM_VERS = 1.0\nCREATION_DATE = 2022-11-06T09:23:57\n" +
				"ORIGINATOR = JSPOC\nTCA = 2022-11-07T00:00:00\n",
			spec: cdmSpec,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := NewScanner([]byte(tt.input), true)
			if _, err := ReadHeader(s, tt.spec); !errors.Is(err, ErrMissingHeaderField) {
				t.Errorf("ReadHeader = %v, want ErrMissingHeaderField", err)
			}
		})
	}
}

// The same MESSAGE_ID line is optional in an orbit message and mandatory in a
// conjunction one, which is the whole reason HeaderSpec exists.
func TestMessageIDPresenceDiffersByStandard(t *testing.T) {
	const withoutID = "CCSDS_OPM_VERS = 3.0\nCREATION_DATE = 2022-11-06T09:23:57\n" +
		"ORIGINATOR = JAXA\nOBJECT_NAME = X\n"

	s := NewScanner([]byte(withoutID), true)
	if _, err := ReadHeader(s, opmSpec); err != nil {
		t.Errorf("an orbit message without MESSAGE_ID was refused: %v", err)
	}
}

func TestReadHeaderRejectsDuplicates(t *testing.T) {
	const input = "CCSDS_OPM_VERS = 3.0\n" +
		"CREATION_DATE = 2022-11-06T09:23:57\n" +
		"ORIGINATOR = JAXA\n" +
		"ORIGINATOR = GSOC\n"

	s := NewScanner([]byte(input), true)
	if _, err := ReadHeader(s, opmSpec); !errors.Is(err, ErrDuplicateHeaderKeyword) {
		t.Errorf("ReadHeader = %v, want ErrDuplicateHeaderKeyword", err)
	}
}

func TestHeaderRoundTrip(t *testing.T) {
	want := Header{
		Version:        "3.0",
		Comments:       []string{"a comment", "another"},
		Classification: "SBU",
		CreationDate:   time.Date(2022, 11, 6, 9, 23, 57, 0, time.UTC),
		Originator:     "JAXA",
		MessageID:      "OPM 201113719185",
	}

	var w Writer
	if err := want.Write(&w, opmSpec); err != nil {
		t.Fatalf("Write: %v", err)
	}
	// A keyword the next section owns, so ReadHeader has somewhere to stop.
	w.Assign("OBJECT_NAME", "OSPREY 5")

	got, err := ReadHeader(NewScanner(w.Bytes(), true), opmSpec)
	if err != nil {
		t.Fatalf("ReadHeader: %v", err)
	}

	if got.Version != want.Version || got.Originator != want.Originator ||
		got.Classification != want.Classification || got.MessageID != want.MessageID {
		t.Errorf("round trip = %+v, want %+v", got, want)
	}
	if !got.CreationDate.Equal(want.CreationDate) {
		t.Errorf("CreationDate = %v, want %v", got.CreationDate, want.CreationDate)
	}
	if len(got.Comments) != len(want.Comments) {
		t.Errorf("Comments = %q, want %q", got.Comments, want.Comments)
	}
}

// Writing a keyword the standard's table does not list must fail rather than
// produce a message the far end will reject.
func TestWriteHeaderRejectsKeywordsTheTableOmits(t *testing.T) {
	h := Header{
		Version:        "1.0",
		Classification: "SBU",
		CreationDate:   time.Date(2022, 11, 6, 9, 23, 57, 0, time.UTC),
		Originator:     "JSPOC",
		MessageID:      "CDM 1",
	}

	var w Writer
	if err := h.Write(&w, cdmSpec); !errors.Is(err, ErrUnknownHeaderKeyword) {
		t.Errorf("writing CLASSIFICATION into a conjunction message = %v, want ErrUnknownHeaderKeyword", err)
	}
}
