package ndm

import (
	"errors"
	"testing"
)

// Clause 7.3.7 allows four line terminators: a bare CR, a bare LF, a CR/LF
// pair and an LF/CR pair. The last one is the reason this package does not use
// bufio.ScanLines — read the ordinary way, an LF followed by a CR looks like a
// line break plus a blank line, and every line number after it is wrong.
func TestScannerHandlesEveryLineTerminator(t *testing.T) {
	tests := []struct {
		name string
		data string
	}{
		{"line feed", "A = 1\nB = 2\nC = 3\n"},
		{"carriage return", "A = 1\rB = 2\rC = 3\r"},
		{"carriage return and line feed", "A = 1\r\nB = 2\r\nC = 3\r\n"},
		{"line feed and carriage return", "A = 1\n\rB = 2\n\rC = 3\n\r"},
		{"no terminator on the last line", "A = 1\nB = 2\nC = 3"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := NewScanner([]byte(tt.data), true)

			want := []struct{ keyword, value string }{{"A", "1"}, {"B", "2"}, {"C", "3"}}
			var got int
			for s.Scan() {
				line := s.Line()
				if line.Kind == Blank {
					t.Fatalf("line %d read as blank; the terminator was split wrongly", line.Number)
				}
				if got >= len(want) {
					t.Fatalf("more lines than expected: %q", line.Text)
				}
				keyword, value, err := line.Assignment()
				if err != nil {
					t.Fatalf("line %d: %v", line.Number, err)
				}
				if keyword != want[got].keyword || value != want[got].value {
					t.Errorf("line %d = %q = %q, want %q = %q",
						line.Number, keyword, value, want[got].keyword, want[got].value)
				}
				if line.Number != got+1 {
					t.Errorf("line number is %d, want %d", line.Number, got+1)
				}
				got++
			}
			if err := s.Err(); err != nil {
				t.Fatalf("Err: %v", err)
			}
			if got != len(want) {
				t.Errorf("read %d lines, want %d", got, len(want))
			}
		})
	}
}

// A blank line is still a blank line: clause 7.3.5 allows one anywhere.
func TestScannerKeepsBlankLines(t *testing.T) {
	s := NewScanner([]byte("A = 1\n\n\nB = 2\n"), true)

	var kinds []Kind
	for s.Scan() {
		kinds = append(kinds, s.Line().Kind)
	}
	if err := s.Err(); err != nil {
		t.Fatalf("Err: %v", err)
	}

	want := []Kind{Assignment, Blank, Blank, Assignment}
	if len(kinds) != len(want) {
		t.Fatalf("read %d lines, want %d", len(kinds), len(want))
	}
	for i := range want {
		if kinds[i] != want[i] {
			t.Errorf("line %d kind = %v, want %v", i+1, kinds[i], want[i])
		}
	}
}

// Clauses 7.4.5 to 7.4.7 make white space around the keyword, around the
// equals sign and before the end of the line insignificant. The examples in
// annex G lean on this heavily — they align their equals signs in a column.
func TestScannerIgnoresAlignmentWhitespace(t *testing.T) {
	tests := []struct{ input, keyword, value string }{
		{"X = 1", "X", "1"},
		{"X=1", "X", "1"},
		{"   X   =   1   ", "X", "1"},
		{"SEMI_MAJOR_AXIS   =  41399.5123            [km]", "SEMI_MAJOR_AXIS", "41399.5123            [km]"},
		{"X                  =   6655.9942        [km]", "X", "6655.9942        [km]"},
	}

	for _, tt := range tests {
		s := NewScanner([]byte(tt.input+"\n"), true)
		if !s.Scan() {
			t.Fatalf("%q: nothing scanned", tt.input)
		}
		keyword, value, err := s.Line().Assignment()
		if err != nil {
			t.Fatalf("%q: %v", tt.input, err)
		}
		if keyword != tt.keyword || value != tt.value {
			t.Errorf("%q = %q = %q, want %q = %q", tt.input, keyword, value, tt.keyword, tt.value)
		}
	}
}

// Clause 7.8.5: the COMMENT keyword repeats on every line, and white space in
// the comment value stays significant.
func TestScannerReadsComments(t *testing.T) {
	tests := []struct{ input, value string }{
		{"COMMENT GEOCENTRIC, CARTESIAN, EARTH FIXED", "GEOCENTRIC, CARTESIAN, EARTH FIXED"},
		{"COMMENT   Generated by GSOC, R. Kiehling", "  Generated by GSOC, R. Kiehling"},
		{"COMMENT", ""},
	}

	for _, tt := range tests {
		s := NewScanner([]byte(tt.input+"\n"), true)
		if !s.Scan() {
			t.Fatalf("%q: nothing scanned", tt.input)
		}
		line := s.Line()
		if line.Kind != Comment {
			t.Fatalf("%q read as %v, want Comment", tt.input, line.Kind)
		}
		if line.Value != tt.value {
			t.Errorf("%q value = %q, want %q", tt.input, line.Value, tt.value)
		}
	}
}

// Clause 7.4.2 exempts the section delimiters from the KVN rule: they stand
// alone with no equals sign.
func TestScannerReadsSectionDelimiters(t *testing.T) {
	for _, keyword := range []string{"META_START", "META_STOP", "COV_START", "COV_STOP", "TRAJ_START"} {
		s := NewScanner([]byte(keyword+"\n"), true)
		if !s.Scan() {
			t.Fatalf("%q: nothing scanned", keyword)
		}
		got, value, err := s.Line().Assignment()
		if err != nil {
			t.Fatalf("%q: %v", keyword, err)
		}
		if got != keyword || value != "" {
			t.Errorf("%q read as %q = %q", keyword, got, value)
		}
	}
}

// An ephemeris row is not KVN (clause 7.4.1.2), so it must not be mistaken for
// one.
func TestScannerReadsDataRowsAsFree(t *testing.T) {
	const row = "2021-06-03T00:00:00.000  6655.9942 -40218.5751 -82.9177  3.11548208 0.47042605 -0.00101495"

	s := NewScanner([]byte(row+"\n"), true)
	if !s.Scan() {
		t.Fatal("nothing scanned")
	}
	if got := s.Line().Kind; got != Free {
		t.Errorf("ephemeris row read as %v, want Free", got)
	}
	if _, _, err := s.Line().Assignment(); !errors.Is(err, ErrNotAnAssignment) {
		t.Errorf("Assignment on a data row = %v, want ErrNotAnAssignment", err)
	}
}

func TestScannerRejectsControlCharacters(t *testing.T) {
	// Clause 7.3.4 names TAB directly.
	s := NewScanner([]byte("X\t= 1\n"), true)
	if s.Scan() {
		t.Error("a line containing a tab was accepted")
	}
	if !errors.Is(s.Err(), ErrControlCharacter) {
		t.Errorf("Err = %v, want ErrControlCharacter", s.Err())
	}
}

// Clause 7.3.2 caps a line at 254 characters, and clause 7.3.3 exempts the
// OCM, so the check is the caller's choice.
func TestScannerLineLengthLimit(t *testing.T) {
	long := "COMMENT " + string(make([]byte, MaxLineLength))
	for i := range long {
		if long[i] == 0 {
			long = long[:i] + "x" + long[i+1:]
		}
	}

	strict := NewScanner([]byte(long+"\n"), true)
	if strict.Scan() {
		t.Error("an over-long line was accepted with the limit on")
	}
	if !errors.Is(strict.Err(), ErrLineTooLong) {
		t.Errorf("Err = %v, want ErrLineTooLong", strict.Err())
	}

	lenient := NewScanner([]byte(long+"\n"), false)
	if !lenient.Scan() {
		t.Errorf("an over-long line was refused with the limit off: %v", lenient.Err())
	}
}

// Clause 7.4.4 requires keywords to be uppercase with no blanks inside.
func TestAssignmentChecksKeywordRules(t *testing.T) {
	tests := []struct {
		input string
		want  error
	}{
		{"x = 1", ErrKeywordNotUppercase},
		{"X Y = 1", ErrKeywordNotUppercase},
		{"= 1", ErrEmptyKeyword},
	}

	for _, tt := range tests {
		s := NewScanner([]byte(tt.input+"\n"), true)
		if !s.Scan() {
			t.Fatalf("%q: nothing scanned", tt.input)
		}
		if _, _, err := s.Line().Assignment(); !errors.Is(err, tt.want) {
			t.Errorf("%q = %v, want %v", tt.input, err, tt.want)
		}
	}
}

func TestUnread(t *testing.T) {
	s := NewScanner([]byte("A = 1\nB = 2\n"), true)

	if !s.Scan() || s.Line().Keyword != "A" {
		t.Fatal("first Scan did not read A")
	}
	s.Unread()
	if !s.Scan() || s.Line().Keyword != "A" {
		t.Fatal("Scan after Unread did not return A again")
	}
	if !s.Scan() || s.Line().Keyword != "B" {
		t.Fatal("second Scan did not read B")
	}
}

func TestWriter(t *testing.T) {
	var w Writer
	w.Assign("CCSDS_OPM_VERS", "3.0")
	w.Comments([]string{"one", "two"})
	w.AssignUnits("X", "6655.9942", "km")
	w.AssignUnits("ECCENTRICITY", "0.020842611", "")
	w.AssignUnits("SOLAR_RAD_COEFF", "1.300", "n/a")
	w.Section("META_START")
	w.Raw("2021-06-03T00:00:00.000 1.0 2.0 3.0")

	want := "CCSDS_OPM_VERS = 3.0\n" +
		"COMMENT one\n" +
		"COMMENT two\n" +
		"X = 6655.9942 [km]\n" +
		"ECCENTRICITY = 0.020842611\n" +
		"SOLAR_RAD_COEFF = 1.300\n" +
		"META_START\n" +
		"2021-06-03T00:00:00.000 1.0 2.0 3.0\n"

	if got := w.String(); got != want {
		t.Errorf("Writer produced\n%q\nwant\n%q", got, want)
	}
}

// Anything the Writer produces must read back as the same lines.
func TestWriterOutputScansBack(t *testing.T) {
	var w Writer
	w.Assign("CCSDS_OPM_VERS", "3.0")
	w.Comment("a comment")
	w.AssignUnits("X", "6655.9942", "km")
	w.Section("META_START")

	s := NewScanner(w.Bytes(), true)
	var kinds []Kind
	for s.Scan() {
		kinds = append(kinds, s.Line().Kind)
	}
	if err := s.Err(); err != nil {
		t.Fatalf("scanning the writer's own output: %v", err)
	}

	want := []Kind{Assignment, Comment, Assignment, Assignment}
	if len(kinds) != len(want) {
		t.Fatalf("read %d lines, want %d", len(kinds), len(want))
	}
	for i := range want {
		if kinds[i] != want[i] {
			t.Errorf("line %d kind = %v, want %v", i+1, kinds[i], want[i])
		}
	}
}
